github_token: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  31656335653463666461333133373733323832646432616238616261323432376530643039333938
  6431363636323637393934326234643663303339666437330a373235396630633066646530306461
  32353666333033643263623236666634653234323861383838653233326461613236316365653534
  3639623966316231320a646236616431386139326631393733643638636231653264343565353230
  65353632643262303935396539313336306136353432303435666266666161623766613265356330
  3136663230633161623838376466343135613536326434323663
