zfix_nodes:
  hosts:
    host.zfix.org:
  vars:
    ansible_user: root
    ansible_port: 222

home_nodes:
  hosts:
    proxmox.internal:
    proxmox-2.internal:
    proxmox-4.internal:
  vars:
    ansible_user: root
