plugin: community.proxmox.proxmox
url: https://proxmox.zfix:8006
validate_certs: false
want_facts: true
exclude_nodes: true
user: ansible@pve
token_id: ansible
token_secret: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  66376439646163666530333162623861646565363766373763303730633836653263656566393062
  3261353866656636373462623031323734663539633537650a396634363039646364343762656236
  62346238396464633165323732666430343564356261363863343933653136303564663030326362
  6534613262333632300a393836353134356431343162623265366464316166323666333838613666
  33353661323066323766613836626263363162666666653833353132313430323466643039626164
  6263393363356535323034643834653061643063613938666635
group_prefix: proxmox_zfix_
filters:
  - "'openwrt' not in (proxmox_tags_parsed|list)"
compose:
  # NOTE(mrksr): The nested quotes are critical here!
  ansible_host: "'host.zfix.org'"
  ansible_port: "'222'"
  ansible_connection: "'community.proxmox.proxmox_pct_remote'"
  ansible_user: "'root'"
