- name: Add ping cronjob for Unifi
  hosts:
    - home_nodes
    - proxmox_home_all_lxc
  gather_facts: false
  roles:
    - unifi-ping-cronjob

- name: Limit journal size
  hosts:
    - proxmox_home_all_lxc
    - proxmox_zfix_all_lxc
  gather_facts: false
  roles:
    - limit-journal-size

- name: Interactive environments for some hosts
  hosts:
    - caddy
    - caddy-zfix
    - homer
  gather_facts: false
  roles:
    - interactive-environment
